/* src: 2016-11-03 17:56:12 */
/* gen: 2016-11-03 18:06:30 */
(function(){function Ma(q,p){return"undefined"!=typeof q?q:p||!1}function J(q,p){for(var w in q)if(q.hasOwnProperty(w)&&"length"!==w&&!1===p.call(q[w],w,q[w]))break}function M(q,p){if(null==q||"object"!==typeof q)return q;if(void 0==p)p=[];else{var w,H=p.length;for(w=0;w<H;w++)if(q===p[w])return q}p.push(q);if("function"==typeof q.clone)return q.clone(!0);if("[object Array]"==Object.prototype.toString.call(q)){H=q.slice();for(w=H.length;w--;)H[w]=M(H[w],p);return H}if(q instanceof Date)return new Date(q.getTime());
if(q instanceof RegExp)return new RegExp(q);if(q.nodeType&&"function"==typeof q.cloneNode)return q.cloneNode(!0);w=Object.getPrototypeOf?Object.getPrototypeOf(q):q.__proto__;w||(w=q.constructor.prototype);var H=Aa(w),K;for(K in q)H[K]=M(q[K],p);return H}function Na(p,v,w){function H(){y({"div[id^=adriver_banner_]":"adriver","div[id^=AdFox_banner_]":"adfox","iframe[id^=AdFox_plug_]":"adfox","ins.adsbygoogle[data-ad-client^=ca-pub-3104790387792468]":"npm","ins[id^=aswift_]>ins[id^=aswift_]>iframe":"adsense",
"div[id^=div-gpt]>div[id^=google_ads_iframe_]>iframe[id^=google_ads_iframe_]":"dfp","div[id^=eplAdDivBanner]>iframe[id^=ifr]":"e-planning"},function(a,b){var c=r.querySelectorAll(a);c.length&&y(c,function(a){if(1==c[a].getAttribute("data-___lx_atf"))return!0;if(T()>ia(c[a]).top){var f=Oa(c[a]);U(c[a]);f&&100<f.height&&(Ba(c[a],"data-___lx_atf",1),K(c[a],{sid:Pa,type:b,h:f.height,w:f.width}))}else return!1})})}function K(a,b){b=b||{};setTimeout(function(a,b){return function(){N(L+"clickiocdn.com/npm_mobile_atf_problems/?rt="+
X()+"&loc="+encodeURIComponent(r.location.href)+Lb(b),function(){})}}(a,b),0)}function G(a,b){var c=!1;if(!a||!~b.indexOf("js/adsbygoogle.js"))return c;var d=Oa(a),f=Oa(a.parentNode),g=320;d&&d.width&&320>d.width?g=300:f&&f.width&&320>f.width&&(g=300);d='style="display:inline-block;width:'+g+'px;height:100px;"';f=/style="display: *?inline-block; *?width: *?\d+?px; *?height: *?\d+?px;"/m;/data-ad-format="(\w|,)+?"/m.test(b)&&(c=b.replace('style="display:block"',""),c=c.replace('style="display:inline-block;"',
d),c=c.replace(/data-ad-format="(\w|,)+?"/mg,""));g=new RegExp('style="display:inline-block;width:'+g+'px;height:100px;"',"m");!g.test(b)&&f.test(b)&&(c=b.replace(f,d));c&&(d=/data-alternate-ad-url="(.+?)"/mg,f=d.exec(c),null!=f&&(c=c.replace(d,'data-alternate-ad-url="$1'+(~f[1].indexOf("?")?"&":"?")+"w="+g+'&h=100"')));return c}function M(a){for(var b=a.c.D.length,c=J(a.ai_min_space),d=J(a.ai_1_space),f=null,g=null,e=!1,k=b?hb(a.c.D[b-1].a):0;!e;){f=a.c.m.shift();if(!f)break;g=hb(f);(e=(b?k+c:d)<
g)&&a.c.C&&a.c.C.length&&y(a.c.C,function(a,b){y(b.za,function(a,c){var d=ia(c).top,f=d+t(c.offsetHeight);if(d>g&&d-b.fa<g||f<g&&f+b.fa>g||d==g||f==g)return e=!1});if(!e)return!1})}return e?f:null}function Qa(a,b){if(!(a.c.K&&!b||a.c.D.length>=a.ai_max_count)&&(a.c.K=!0,null==a.c.m&&(a.c.m=r.querySelectorAll(a.location),a.c.m&&a.c.m.length&&(a.c.m=Array.prototype.slice.call(a.c.m,0)),a.L&&y(a.c.m,function(b,c){T()>ia(c).top&&a.c.m.splice(b,1)})),a.c.m.length)){if(n(a.ai_border_check)&&null==a.c.C){a.c.C=
[];var c=a.ai_border_check,c=c.split(","),d=J(a.ai_min_space);y(c,function(b,c){var f=d;~c.indexOf(":")&&(c=c.split(":"),f=J(c[1]),c=c[0]);var g=r.querySelectorAll(c);g&&g.length&&a.c.C.push({Ma:c,fa:f,za:g})})}var c=M(a),f=null;if(c){var f={},g=1+a.c.D.length;f.a=z("div");f.a.setAttribute("data-cnt",g);f.a.className="__lxG__multi __lxG__multi_"+a.id;c.parentNode.insertBefore(f.a,c.nextSibling);a.c.source?(V(f.a,a.c.source),I(a.c)):N(L+"clickiocdn.com/multishows/"+a.c.id+"."+g+"/"+ja(),function(){});
a.c.D.push(f);n(a.refresh)&&(a.l=setTimeout(Mb(a,g),1E3*a.refresh))}n(a.ai_clone_source)&&f&&a.c.m.length&&ib(a)&&Qa(a,!0);a.c.K=!1}}function ib(a){var b=a.c.D;return b&&b.length?hb(b[b.length-1].a)+J(a.ai_min_space)<t(!ra||g.opera||sa||"unknown"!=Y()?F.scrollTop:R.scrollTop)+T()*(a.ai_preload+1):!1}function J(a){a=n(a,!1);if(!1!==a){var b=/((\d|\.|,)+?)s/im.exec(a);null!=b?a=Math.round(parseFloat(b[1])*T()):a=t(a)}return a}function ha(a,b,c){.1<(b-a.a.volume)*c?(a.a.volume=O(a.a.volume+.1*c,2),Z[a.g]=
setTimeout(function(){ha(a,b,c)},25)):a.a.volume=b}function Aa(a){Z[a.g]&&clearTimeout(Z[a.g]);Z[a.g]=setTimeout(function(){0<a.a.volume&&ha(a,0,-1)},100)}function La(a){Z[a.g]&&clearTimeout(Z[a.g]);Z[a.g]=setTimeout(function(){1>a.a.volume&&ha(a,.6,1)},100)}function za(a){jb(a,-1,function(){return function(){Ra(g,"focus scroll",a.la);delete Z[a.g];delete ta[a.g];delete Ca[a.g];a.j.ca?a.A.parentNode.removeChild(a.A):(a.href.parentNode.removeChild(a.href),a.V.parentNode.removeChild(a.V),a.S.parentNode.removeChild(a.S),
a.P.parentNode.removeChild(a.P),a.O.parentNode.removeChild(a.O))}}())}function Ma(a,b){var c=b.type;if("pause"!=c||a.a.duration!=a.a.currentTime){"play"==c&&0==a.a.currentTime&&(c="started");if("timeupdate"==c){if(a.j.F)for(var d in a.j.F)if(a.j.F.hasOwnProperty(d)){var f=t(d.replace("_",""));if(a.a.duration*f/100<=a.a.currentTime){for(f=a.j.F[d].length;f--;)z("img").src=a.j.F[d][f];delete a.j.F[d]}}100!=a.j.ba&&!a.U&&a.a.duration*a.j.ba/100<=a.a.currentTime&&(a.U=!0,setTimeout(function(){N(a.j.ka,
function(){})},0))}"started"==c&&setTimeout(function(){N(a.j.Fa,function(){})},0);"ended"==c&&(a.U||setTimeout(function(){N(a.j.ka,function(){})},0),za(a))}}function Na(a){if(!a.u){for(var b=!1,c=T(),d=a.a.getClientRects(),f=0,g=d.length;f<g;f++){var e=d[f];if(0<=e.top&&e.top<c){b=!0;break}}b&&jb(a,1,function(){return function(){kb(a)}}())}a.u&&a.a.duration!=a.a.currentTime&&((b=Nb(a.a))&&a.a.paused?a.a.play():b||a.a.pause())}function kb(a){ta[a.g]&&clearTimeout(ta[a.g]);ta[a.g]=setTimeout(function(){Na(a)},
50)}function jb(a,b,c){Ca[a.g]&&clearTimeout(Ca[a.g]);var d=U(a.A),f=t(d.height),g=a.j.ca?0:120;1==b&&f<a.a.height||-1==b&&f>g?(a.A.style.height=f+5*b+"px",1==b?a.A.style.opacity=parseFloat(d.opacity)+O(1/(a.a.height/5),3)*b:(d=U(a.href),a.href.style.opacity=parseFloat(d.opacity)+O(1/((a.a.height-g)/5),3)*b,a.V.style.opacity=a.href.style.opacity,a.S.style.opacity=a.href.style.opacity,a.P.style.opacity=a.href.style.opacity,a.O.style.opacity=a.href.style.opacity),Ca[a.g]=setTimeout(function(){jb(a,
b,c)},10)):(1==b?(a.u=1==b,a.A.style.opacity=t(a.u)):-1==b&&0==g&&(a.A.style.display="none"),c())}function Dc(a,b){if(!Ob){Ob=!0;var c=z("link");c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");c.href=L+"s.clickiocdn.com/images/i/video26/videostyle.css";Da.appendChild(c)}var d={g:X(),u:!1};Z[d.g]=ta[d.g]=Ca[d.g]=!1;d.j=b;d.U=!1;c=z("div");c.style.cssText=b.na;c.style.width=b.R+"px";c.style.height="0px";c.style.margin="0 auto";c.style.textAlign="center";c.style.display="block";c.style.overflow=
"hidden";c.style.opacity=0;c.style.position="relative";x(c,"lx_amn_inlvid");var f=z("a");f.href="javascript:void(0);";x(f,"ico");f.appendChild(z("span"));var D=z("a");D.href=b.aa;D.target="_blank";x(D,"vid");var e=z("video");e.width=b.R;e.height=Pb(b.R/(b.Ha/b.Ea));e.controls=!1;e.autoplay=!1;e.volume=0;var k=z("source");k.src=b.Ga;e.appendChild(k);d.a=e;d.A=c;d.href=D;d.V=f;d.nextSibling=a.nextSibling;d.previousSibling=a;k=z("a");k.href="javascript:void(0);";k.innerHTML="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";
A(k,"click",function(){return function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;za(d);return!1}}());x(k,"cls");d.S=k;b.ra&&(k.style.display="none");var l=z("a");l.href="javascript:void(0);";l.innerHTML='<span class="bg_lnk"></span><span class="txt_lnk">\u0420\u0435\u043a\u043b\u0430\u043c\u0430</span>';x(l,"adv");d.P=l;b.sa&&(l.style.display="none");var m=z("a");m.href="javascript:void(0);";m.innerHTML='<span class="bg_lnk"></span><span class="txt_lnk">'+d.j.ga+"</span>";x(m,"adv_txt");
d.O=m;d.j.ga||(m.style.display="none");var h=z("div");x(h,"dsc");h.innerHTML='<span><a href="http://video.adlabsnetworks.com/?utm_source=partners&utm_medium=logo" target="_blank">Powered by</a></span>';var n=z("a");n.href=b.aa;n.target="_blank";h.appendChild(n);n.innerHTML="\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442 \u0440\u0435\u043a\u043b\u0430\u043c\u043e\u0434\u0430\u0442\u0435\u043b\u044f";A(e,"play pause ended timeupdate",function(){return function(a){Ma(d,
a)}}());A(e,"mouseover",function(){return function(){La(d)}}());A(e,"mouseout",function(){return function(){Aa(d)}}());A(D,"click",function(){return function(){d.a.pause();return!0}}());d.la=function(){return function(){kb(d)}}();A(g,"focus scroll",d.la);D.appendChild(e);c.appendChild(k);c.appendChild(l);c.appendChild(m);c.appendChild(f);c.appendChild(D);c.appendChild(h);a.parentNode.insertBefore(c,a.nextSibling);ta[d.g]=setTimeout(function(){kb(d)},50)}function Qb(a){var b=new Date,c=b.getTime();
b.setTime(c+2592E6);S.set(lb,a,b,"/");S.set(Rb,S.get(Sb,0),b,"/");S.set(Sb,c,b,"/")}function Mb(a,b){return function(){if(a.o)return!1;a.l&&clearTimeout(a.l);a.o=!0;var c=null;y(C,function(b){if(C[b]===a)return c=b.replace("_",""),!1});!1!==n(a.refresh_limit)&&a.refresh_limit--;N(L+"clickiocdn.com/multishows/"+c+(b?"."+b:"")+"/"+ja(),function(){a.o=!1})}}function aa(a,b){h(g.__lxG__.multishows_params)&&n(g.__lxG__.multishows_params.preventautorefresh)||!n(a.refresh)||!n(a.refresh_limit,!0)||(a.l=
setTimeout(Mb(a,b||null),1E3*a.refresh))}function Ec(a){return function(){if(a.o)return!1;a.l&&clearTimeout(a.l);a.o=!0;N(L+"clickiocdn.com/multishows/"+a.I+"/"+ja(),function(){})}}function Tb(a,b){setTimeout(function(){var c=parseInt(a.style.right);0<b&&0==c||0>b&&c==mb(a)||(c+=6*b,0<c&&(c=0),c<mb(a)&&(c=mb(a)),a.style.right=c+"px",Tb(a,b))},10)}function Fc(a){return function(){ca()?x(a.a,"lxm_landscape"):Ea(a.a,"lxm_landscape");r.getElementById("lx_dbg_fullscreen")&&(r.getElementById("lx_dbg_fullscreen").innerHTML=
a.a.className);return!1}}function Gc(a){return function(b){b.stopPropagation();var c=E("lx_links_position",a.a)[0];nb(c,"anishow")?(x(c,"anihide"),Ea(c,"anishow")):(x(c,"anishow"),Ea(c,"anihide"));b.preventDefault();return!1}}function Hc(){return function(a){a.stopPropagation();var b=h(this.style)?t(n(this.style.right,0)):0;return t(a.pageX)-t(this.offsetLeft)<this.getAttribute("triggerWidth")?(b!=this.getAttribute("baseStyleRight")&&0!=b||Tb(this,0==b?-1:1),a.preventDefault(),!1):!0}}function Ic(a,
b){return function(c){if(c||g.event)c=c||g.event,c.stopPropagation?c.stopPropagation():c.cancelBubble=!0,c.preventDefault&&c.preventDefault();c=E("lxm_sl",a.a)[0];c.style.display="";c=E("lxm_button",c)[0];c.href=b.href;c.title=b.title;return!1}}function Jc(a){return function(b){if(b||g.event)b=b||g.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;E("lxm_sl",a.a)[0].style.display="";return!1}}function Kc(a){return function(b){if(b||g.event)b=b||g.event,b.stopPropagation?b.stopPropagation():
b.cancelBubble=!0;a.a.style.display="none";a.G=!0;a.W&&(b=ob(),pb?Ba(b,"content",pb):b.parentNode.removeChild(b));if(Fa(a.closeTimeout)&&(b=Fa(a.closeTimeout))){var c=new Date;c.setTime(c.getTime()+6E4*b);S.set("_lxblockignore_"+a.I,1,c,"/")}return!0}}function Ub(a,b,c){!1!==c&&x(a,"lxm_"+b+"_"+(.5*Math.ceil(parseFloat(c)/.5)).toString().replace(".","_"))}function Vb(a){for(var b=!1,c=Ga("meta",!0),d=c.length;d--;)if(h(c[d].name)&&"viewport"==c[d].name){var f=c[d].content;if(~f.indexOf(a)&&(f=(new RegExp(a+
" *?= *?(.+?)(?:[, ]|$)","m")).exec(f),null!=f)){b=f[1];break}}return b}function ba(){if(-1===Sa){Sa=!1;for(var a=Ga("meta",!0),b=a.length;b--;)if(h(a[b].content)){var c=a[b].content;if(~c.indexOf("width=device-width")||~c.indexOf("initial-scale=1")||~c.indexOf("user-scalable=no")){Sa=!0;break}}}return Sa}function Lc(){var a=Y(),b=Wb(),c=1,c=ba()?1/b:(1.144>b?1:2.75<b?1.26:4.431914*Math.pow(b,8)-65.6671503*Math.pow(b,7)+417.3583138*Math.pow(b,6)-1484.928018*Math.pow(b,5)+3233.105604*Math.pow(b,4)-
4410.2163548*Math.pow(b,3)+3680.9724495*Math.pow(b,2)-1719.2504263*b+345.6426082)/b;"android"==a&&3>ka&&!ca()?c=1.3*b:ca()&&(c*=1.15);return c=O(100*c)}function Wb(){if(Xb!=qb){var a=Y(),b=1,c=ba()?1:window.devicePixelRatio;"ios"==a&&~da.indexOf("iphone")&&!ba()&&(c=2);b=R.clientWidth/g.innerWidth/c;if(~da.indexOf("ipad")||"android"==a&&la&&1<c)b*=c;ca()&&"android"==a&&!ba()?b*=2:ca()&&"android"==a&&ba()&&(b*=.85);!ca()&&la&&"android"==a?b/=(ka(),1.5):ca()&&la&&"android"==a&&!ba()&&(b/=4<=ka()?1.75:
1.5);Yb=O(100*b)/100;Xb=qb}return Yb}function ca(){var a=Y(),b=0===window.orientation||180===window.orientation;return la&&"android"==a&&4<=ka()?!b:la&&"android"==a?b:!b}function Y(){if(!Ta){Ta="unknown";for(var a=[["android","android"],["ipad","ios"],["iphone","ios"],["ipod","ios"]],b=0;b<a.length;b++)if(~da.indexOf(a[b][0])){Ta=a[b][1];break}}return Ta}function ka(){if(!1===Ua){var a=Y();Ua=0;"android"==a&&(Ua=parseFloat(da.slice(da.indexOf("android")+8)))}return Ua}function Zb(a){if(!rb){var b=
0;rb=!0;qb++;for(var c in P)if(P.hasOwnProperty(c)){var d=P[c];if(!d.ea&&!d.W&&!d.G){var f=d.a,D=Wb(),e=Lc(),k=[g.pageXOffset,g.pageYOffset],l=[g.pageXOffset,g.pageYOffset+g.innerHeight];f.style.width=k[0]+g.innerWidth-k[0]+"px";"android"==Y()&&4<=ka()||(f.style.left=k[0]+"px",f.style.top=d.ua?l[1]-f.offsetHeight+"px":k[1]+"px");ca()?x(f,"lxm_landscape"):Ea(f,"lxm_landscape");D=Math.ceil(d.ta/D);f.style.height=D+"px";Va(d.wa,"height",D+"px");Va(d.ya,"lineHeight",D+"px");d.Z&&(f=Pb(D*(ba()?.8:.95))+
"px",d.Z.style.height=f,d.Z.style.width=f);f=ba()?100:50>e?80:100;Va(d.va,"fontSize",e+"%");Va(d.xa,"lineHeight",f+"%");b++}}b&&a&&(sb&&clearTimeout(sb),sb=setTimeout(function(){Zb(!1)},250));rb=!1}}function $b(){tb&&clearTimeout(tb);tb=setTimeout(function(){Zb(!0)},250)}function Mc(a,b){var c=ac(a.a);if(b){for(var d in c)c.hasOwnProperty(d)&&t(c[d])&&"lxm_"==d.substring(0,4)&&x(a.a,d);x(a.a,"lxm_os_"+Y());ba()&&x(a.a,"lxm_meta_set");h(g.devicePixelRatio)&&x(a.a,"lxm_pixel_ratio_"+Math.ceil(g.devicePixelRatio))}for(var f=
E("lxm_js_block_close",a.a),D=f.length;D--;)A(f[D],"click",Kc(a));a.ea=!1;a.W=!1;if(Fa(c.lxm_fullscreen)){a.W=!0;bc();f=E("lxm_sl_trigger",a.a);for(D=f.length;D--;)A(f[D],"click",Ic(a,f[D]));var e=E("lxm_sl",a.a)[0],c=E("lxm_button_close",e)[0];A(c,"click",function(){return function(){e.style.display="none"}}());h(screen.width)&&x(a.a,"lxm_scr_"+250*Math.ceil(Math.max(screen.width,screen.height)/250));c=g.innerHeight||0;x(a.a,"lxm_scr_width_"+100*Math.ceil((g.innerWidth||0)/100));x(a.a,"lxm_scr_height_"+
100*Math.ceil(c/100));Ub(a.a,"minscale",Vb("minimum-scale"));Ub(a.a,"initscale",Vb("initial-scale"));c="lxm_zoom_"+(.25*Math.ceil(R.clientWidth/g.innerWidth/.25)).toString().replace(".","_");x(a.a,c);c=E("lx_hide_logo",a.a);for(f=c.length;f--;)A(c[f],"click",Gc(a));c=Fc(a);f=["orientationchange","touchmove","touchend","scroll","resize"];for(d in f)f.hasOwnProperty(d)&&A(g,f[d],c);c()}else{f=E("lxm_sl_trigger",a.a);for(D=f.length;D--;)A(f[D],"click",Jc(a));if(Fa(c.lxm_static))for(a.ea=!0,c=E("lxm_banner_sc",
a.a),f=c.length;f--;)A(c[f],"click",Hc());else{b&&("android"==Y()&&4<=ka()||(a.a.style.position="absolute",a.a.style.bottom="auto"),a.ta=Fa(c.initheight),a.ua=nb(a.a,"lxm_bottom"),a.Z=nb(a.a,"lxm_tizer")?E("lxm_tizer_img",a.a)[0]:!1,a.va=E("lxm_js_fontsize",a.a),a.xa=E("lxm_js_lineheight",a.a),a.ya=E("lxm_js_lineheightpx",a.a),a.wa=E("lxm_js_height",a.a));if(!cc){if("android"==Y()&&3>ka())d=z("meta"),d.name="viewport",d.content="width=device-width",r.head.appendChild(d);else for(d in f=["orientationchange",
"touchmove","touchend","scroll","resize"],f)f.hasOwnProperty(d)&&A(g,f[d],$b);cc=!0}h(a.refresh)&&a.refresh&&(a.l&&clearTimeout(a.l),a.l=setTimeout(Ec(a),1E3*a.refresh));$b()}}}function bc(a){var b=ob();b&&(pb=b.getAttribute("content"));a=a||"width=device-width";b?Ba(b,"content",a):(r.getElementsByTagName("head").length||r.insertBefore(z("head"),r.getElementsByTagName("body")[0]),b=z("meta"),b.name="viewport",b.content=a,Ga("head").appendChild(b))}function ob(){for(var a=!1,b=Ga("meta",!0),c=b.length;c--;)if(h(b[c].name)&&
"viewport"==b[c].name){a=b[c];break}return a}function ub(a,b){a.u=!1;h(a.v)&&clearInterval(a.v);clearTimeout(a.l);a.H&&clearTimeout(a.H);a.v=setInterval(function(){var c=dc(a),d=c-22;c>=-a.width&&d>-a.width?(a.J=!0,a.a.style[a.side]=d+"px"):(clearInterval(a.v),a.J=!1,a.a.style[a.side]=-a.width+"px",a.a.style.display="none",h(b)&&b());Wa&&Xa(a)()},15)}function Nc(a){return function(){a.H&&clearTimeout(a.H);a.X=!1;a.Y&&N(vb+encodeURIComponent(a.Y),function(){})}}function Oc(a){a.u=!0;h(a.v)&&clearInterval(a.v);
clearTimeout(a.l);a.l=setTimeout(ec(a),1E3*a.refresh);a.a.style.display="block";a.v=setInterval(function(){var b=dc(a),c=b+22;0>b&&0>c?(a.J=!0,a.a.style[a.side]=c+"px"):(clearInterval(a.v),a.J=!1,a.a.style[a.side]="0px",a.X&&(a.H=setTimeout(Nc(a),1E3)));Wa&&Xa(a)()},15)}function dc(a){var b=0;return b=Wa?a.a[a.side+"Offset"]:t(a.a.style[a.side])}function fc(a){return function(){h(a.da)&&clearTimeout(a.da);a.da=setTimeout(Xa(a),100)}}function Xa(a){return function(){a.a[a.side+"Offset"]=t(a.a.style[a.side]);
var b={bottom:!0};"left"==a.side&&(b.left=!0);"right"==a.side&&(b.right=!0);pinBlock(a.a,b)}}function gc(a){return function(){if(!a.G&&!a.o){var b=t(R.scrollTop?R.scrollTop:F.scrollTop);!a.u&&b>=a.limit?Oc(a):a.u&&b<a.limit&&ub(a)}}}function ec(a){return function(b){if(b||g.event)b=b||g.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;clearTimeout(a.l);a.o=!0;ub(a,function(){N(L+"clickiocdn.com/multishows/"+a.I+"/"+ja(),function(){})})}}function Pc(a){return function(b){if(b||g.event)b=
b||g.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;a.G=!0;ub(a);b=new Date;b.setTime(b.getTime()+5925924E4);S.set(wb(),1,b,"/")}}function Qc(a,b){b&&(A(r,"scroll",gc(a)),Wa&&(Xa(a)(),A(g,"resize",fc(a)),A(g,"scroll",fc(a))));for(var c=E("close",a.a),d=c.length,f=0;f<d;f++)A(c[f],"click",Pc(a));c=E("ref",a.a);d=c.length;for(f=0;f<d;f++)A(c[f],"click",ec(a))}function I(a,b){h(a.counters)&&(b=b||r,y(a.counters,function(a,d){z("img",b).src=d+"&_lxrnd_="+X()}));3>=O(100*Math.random())&&
hc("//pixel.adsafeprotected.com/jload?anId=924203&pubId="+Pa+"&placementId="+n(a.id,0)+"")}function Rc(a){y(a,function(a,c){if(n(c.id)){var d=c.id+(n(c.sub_id)?"."+c.sub_id:"");null===ma&&(ma={});ma[d]=c}else~Sc.indexOf(n(c.type))?xb.push(c):~Tc.indexOf(n(c.type))&&xb.push(c)})}function Uc(a,b){b=b||g.event;var c=b.target,d=z("A");d.id="FakeLink";F.appendChild(d);var f=r.createEvent("MouseEvents");f.initMouseEvent("click",c?!0:!1,!0,g,1,!1,!1,!1,!1,!0,!1,!1,!1,!1,null);d.href=a;d.target="_blank";
d.dispatchEvent(f)}function Vc(a){var b=g.open("about:blank",u+"popunder","toolbar=0,scrollbars=1,location=1,statusbar=1,menubar=0,resizable=1,top=0,left=0,width="+g.screen.availWidth+",height="+g.screen.availHeight+"");if(b){b.blur();try{b.opener.focus()}catch(c){}b.location=a}}function ic(a){var b=g.open("about:blank",u+"popunder","resizable=1,toolbar=0,location=1,menubar=1,directories=0,width="+g.screen.availWidth+",height="+g.screen.availHeight+",scrollbars=1");b&&(b.blur(),b.ma=function(c){with(c)Params=
c.Ia,Main=function(){h(window.mozPaintCount)&&window.open("about:blank").close();try{opener.window.focus()}catch(c){}b.location=a},Main()},b.ma(b),b.blur())}function jc(){ua&&clearTimeout(ua);ua=setTimeout(Wc,500)}function Wc(){ua&&(clearTimeout(ua),ua=null);for(var a=na.length,b=0;b<a;b++)if(na[b]){var c=na[b][1];Nb(na[b][0])&&(delete na[b],N(vb+encodeURIComponent(c),function(){}))}}function Nb(a){if(0===a.offsetWidth||0===a.offsetHeight)return!1;for(var b=T(),c=ra&&!g.opera?R.clientWidth:F.clientWidth,
d=a.getClientRects(),f=0,D=d.length;f<D;f++){var e=d[f],k=e.height?e.height:e.bottom-e.top,l=e.width?e.width:e.right-e.left,l=0<=e.left+.25*l&&e.left+.75*l<c;if(k=0<=e.top+.25*k&&e.top+.75*k<b&&l){e=r.elementFromPoint((e.left+e.right)/2,(e.top+e.bottom)/2);if(e===a)e=!0;else a:{if(e)for(e=e.parentNode;null!=e;){if(e==a){e=!0;break a}e=e.parentNode}e=!1}k=e}if(k)return!0}return!1}function E(){}function T(){return ra&&!g.opera?R.clientHeight:F.clientHeight}function Xc(a,b){function c(b){var c=U(a)["line-height"];
"normal"==c?c=1.2*yb(U(a)["font-size"]):/[a-z]+/im.test(c)?c=parseFloat(c):c=yb(U(a)["font-size"])*parseFloat(c);return Math.ceil(c*b)}function d(b){var c=b.lastChild&&!b.lastChild.nodeValue&&b.lastChild.innerHTML?b.lastChild.innerHTML:b.lastChild.nodeValue;if(b.lastChild.children&&0<b.lastChild.children.length)return d(Array.prototype.slice.call(b.children).pop());if(b.lastChild&&c&&""!=c&&c!=e.N)return b.lastChild;b.lastChild.parentNode.removeChild(b.lastChild);return d(a)}function f(b,c){if(c&&
b){var k=!(b.nodeValue||!b.innerHTML),l=(k?b.innerHTML:b.nodeValue).replace(e.N,"");n||(0<m.length?h=m.shift():h="",n=l.split(h));1<n.length?(r=n.pop(),g(b,n.join(h),k)):n=null;if(n){if(a.clientHeight<=c)if(0<=m.length&&""!=h)g(b,n.join(h)+h+r,k),n=null;else return a.innerHTML}else""==h&&(g(b,"",k),b=d(a),m=e.ja.slice(0),h=m[0],r=n=null);return f(b,c)}}function g(a,b,c){c?a.innerHTML=b+e.N:a.nodeValue=b+e.N}b=b||{};var e={pa:b.clamp||2,$:"undefined"!=typeof b.$?b.$:!0,ja:[".","-","\u2013","\u2014",
" "],N:"\u2026"},k=a.style,l=e.pa,m=e.ja.slice(0),h=m[0],n,r;"undefined"!=typeof a.style.webkitLineClamp&&e.$?(k.overflow="hidden",k.textOverflow="ellipsis",k.webkitBoxOrient="vertical",k.display="-webkit-box",k.webkitLineClamp=l):(k=c(l),k<=a.clientHeight&&f(d(a),k))}function Yc(a,b,c){var d=b||1;if(va.length){for(var f in va.Ca)va.Ca.hasOwnProperty(f)&&Ra(g,"resize orientationchange",va[f]);va=[]}c.min=c.min||Number.NEGATIVE_INFINITY;c.max=c.max||Number.POSITIVE_INFINITY;y(a,function(){function a(){var f=
Math.round(Math.max(Math.min(yb(U(b).width)/(10*d),parseFloat(c.max)),parseFloat(c.min)));b.style.fontSize=f+"px"}var b=this;a();va.push(a);A(g,"resize orientationchange",a)})}function oa(a,b,c,d,f,g){g=g||!1;f=f||r;f=z("iframe",f);f.id=a.id+"_frame";f.sandbox="allow-same-origin allow-scripts allow-popups allow-forms";h(c)&&(f.style.width=c+"px");h(d)&&(f.style.height=d+"px");f.setAttribute("allowtransparency","true");f.setAttribute("marginwidth","0");f.setAttribute("marginheight","0");f.setAttribute("hspace",
"0");f.setAttribute("vspace","0");f.setAttribute("frameborder","0");f.setAttribute("scrolling","no");a.appendChild(f);g?f.src=b:(a=f.contentDocument,a.open(),a.write(b),a.close())}function hb(a){return ia(a).top+t(a.offsetHeight)}function ia(a){a.getBoundingClientRect?(a=a.getBoundingClientRect(),a={top:Math.round(a.top+(g.pageYOffset||r.scrollTop||F.scrollTop)-(r.clientTop||F.clientTop||0)),left:Math.round(a.left+(g.pageXOffset||r.scrollLeft||F.scrollLeft)-(r.clientLeft||F.clientLeft||0))}):a=zb(a);
return a}function Zc(){}function yb(a){return parseFloat(a)}function t(a){return parseInt(a,10)}function O(a,b){if(h(b)){var c;c=Math.pow(10,b);return Math.round(a*c)/c}return Math.round(a)}function Pb(a){return Math.floor(a)}function X(){return(new Date).getTime()%1E7*100+O(99*Math.random())}function h(a){return"undefined"!=typeof a}function n(a,b){return h(a)?a:b||!1}function Fa(a){return h(a)?t(a):!1}function Ga(a,b,c){c=c||r;return b?c.getElementsByTagName(a):c.getElementsByTagName(a)[0]}function mb(a){return a.getAttribute("baseStyleRight")}
function Ba(a,b,c){a.setAttribute(b,c+"")}function y(a,b){for(var c in a)if(a.hasOwnProperty(c)&&"length"!==c&&!1===b.call(a[c],c,a[c]))break}function $c(a){a=a.split("+").join(" ");for(var b={},c,d=/[?&]?([^=]+)=([^&]*)/g;c=d.exec(a);)b[decodeURIComponent(c[1])]=decodeURIComponent(c[2]);return b}function N(a,b){b||(b=function(){});kc()&&sa&&!/\bclickio\w+?\b/im.test(a)?ad(a,b):hc(a,b)}function hc(a,b){b||(b=function(){});var c=z("script");c.setAttribute("type","text/javascript");c.setAttribute("src",
a);c.setAttribute("async","async");h(c)&&(ea?c.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||setTimeout(b,0)}:c.onload=function(){setTimeout(b,0)},Da.appendChild(c))}function ad(a,b){b||(b=function(){});var c="ws"+("https:"==g.top.location.protocol?"s":"");a=a.replace(L,c+"://");a=a.replace(/wss?:\/\/([a-zA-Z0-9-.]+)\//img,c+"://$1/ws/");var c=new Worker(URL.createObjectURL(new Blob(['var r=null,s=new WebSocket("'+a+'");s.onmessage=function(e){if(e.data){postMessage(e.data);r=e.data;s.close();}};onmessage=function(e){if(e.data=="!"){close();};if(e.data=="?"&&r){postMessage(r);}}'],
{type:"application/javascript"}))),d=setInterval(function(a){return function(){a.postMessage("?")}}(c),50);c.onmessage=function(a,b,c){return function(d){a.onmessage=function(){};clearInterval(c);a.postMessage("!");bd(d);b()}}(c,b,d)}function bd(a){a=a.data;var b=z("script");b.type="text/javascript";b.appendChild(r.createTextNode(a));Da.appendChild(b)}function wa(a){var b;b=b||r;var c=z("style",b);c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");Da.appendChild(c);ea?c.styleSheet.cssText=
a:c.appendChild(b.createTextNode(a))}function Va(a,b,c){if(a.length)for(var d=a.length;d--;)a[d].style[b]=c}function lc(){var a=!1,b=navigator,c=null;if(h(b.plugins)&&"object"==typeof b.plugins["Shockwave Flash"])!(c=b.plugins["Shockwave Flash"].description)||h(b.mimeTypes)&&b.mimeTypes["application/x-shockwave-flash"]&&!b.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(c=c.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),a=[0,0,0],a[0]=t(c.replace(/^(.*)\..*$/,"$1")),a[1]=t(c.replace(/^.*\.(.*)\s.*$/,
"$1")),a[2]=/[a-zA-Z]/.test(c)?t(c.replace(/^.*[a-zA-Z]+(.*)$/,"$1")):0);else if(h(g.ActiveXObject))try{if(c=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))c=c.split(" ")[1].split(","),a=[t(c[0]),t(c[1]),t(c[2])]}catch(d){}return a=!1!==a?a.join("."):a}function cd(){var a=lc(),b=["10","0","42"];if(!1===a)return!1;a=a.split(".");b[0]=parseInt(b[0],10);b[1]=parseInt(b[1],10)||0;b[2]=parseInt(b[2],10)||0;return a[0]>b[0]||a[0]==b[0]&&a[1]>b[1]||a[0]==b[0]&&a[1]==b[1]&&a[2]>=
b[2]?a.join("."):!1}function A(a,b,c){if(a){"[object NodeList]"!=Object.prototype.toString.call(a)&&(a=[a]);b=b.split(" ");var d=b.length,f;for(f=0;f<d;f++)y(a,function(){this.addEventListener?this.addEventListener(b[f],c,!1):this.attachEvent("on"+b[f],c)})}}function Ra(a,b,c){if(a){"[object NodeList]"!=Object.prototype.toString.call(a)&&(a=[a]);b=b.split(" ");var d=b.length,f;for(f=0;f<d;f++)y(a,function(){this.detachEvent?this.detachEvent("on"+b[f],c):(this.removeEventListener(b[f],c,!0),this.removeEventListener(b[f],
c))})}}function Ea(a,b){b=b.split(" ");for(var c=0;c<b.length;c++)a.className=a.className.replace(new RegExp("\\b"+b[c]+"\\b","g"),"").replace(/\s+/g," ").replace(/(^ | $)/g,"")}function x(a,b){Ea(a,b);b=b.split(" ");for(var c=0;c<b.length;c++)a.className+=" "+b[c];a.className=a.className.trim()}function nb(a,b){return(new RegExp("\\b"+b+"\\b","im")).test(a.className)}function V(a,b,c){c=c||r;a.innerHTML=b;b=[];for(var d=a.childNodes,f=0;d[f];f++){var g=d[f];!g.nodeName||"script"!==g.nodeName.toLowerCase()||
g.type&&"text/javascript"!==g.type.toLowerCase()||b.push(d[f])}for(var e in b){var d=b[e].parentNode?b[e].parentNode.removeChild(b[e]):b[e],f=(f=c)||r,g=a||Da,k=z("script",f);k.type="text/javascript";if(h(d.src)&&d.src)k.src=d.src,k.className=d.className;else{var l=d.text||d.textContent||d.innerHTML||"";k.className=d.className;k.appendChild(f.createTextNode(l))}g.appendChild(k)}}function z(a,b){b=b||r;return b.createElement(a)}function kc(){if(null!==pa)return pa;var a="pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links";
h(g.__lxG__.adbc)&&(a+=" "+g.__lxG__.adbc);var b=z("div");b.setAttribute("style","width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -10000px !important; ");b.setAttribute("class",a);h(g.__lxG__.adbi)&&(b.id=g.__lxG__.adbi);F.appendChild(b);var a=!0,c=!1;h(g.__lxG__.adbh)?(b.innerHTML=g.__lxG__.adbh,h(g.__lxG__.adbhs)&&(c=b,b=b.querySelector(g.__lxG__.adbhs))):h(g.__lxG__.adbs)&&(a=!1,b=r.querySelector(g.__lxG__.adbs));pa=!1;if(null!==F.getAttribute("abp")||
null===b.offsetParent||0==b.offsetHeight||0==b.offsetLeft||0==b.offsetTop||0==b.offsetWidth||0==b.clientHeight||0==b.clientWidth)pa=!0;if(!pa){var d=U(b);if("none"==d.getPropertyValue("display")||"hidden"==d.getPropertyValue("visibility"))pa=!0}a&&F.removeChild(b);c&&F.removeChild(c);return pa}function ja(a){a=a||!1;var b="",b="?rt="+X();r.referrer&&(b+="&r="+encodeURIComponent(r.referrer));qa&&(b+="&recurring=1");mc&&(b+="&flash="+encodeURIComponent(mc));ea&&(b+="&isie=1");"https:"==g.location.protocol&&
(b+="&https=1");Ab&&(b+="&md="+encodeURIComponent(Ab));b+="&f="+W;h(screen.width)&&(b+="&scr="+encodeURIComponent(screen.width+"x"+screen.height));h(g.innerWidth)&&(b+="&wnd="+encodeURIComponent(g.innerWidth+"x"+g.innerHeight));kc()&&(b+="&bl=1");nc&&(nc=!1,b+="&add=1");S.T(wb())&&(b+="&ignorefloat=1");Bb.length&&(b+="&ignore="+Bb.join(";"));h(g.__lxG__.multishows_params)&&(b+=Lb(g.__lxG__.multishows_params));g[u].bids.start&&(b+="&pbjs=1");a&&(a=dd(a))&&(b+="&bids="+encodeURIComponent(a));return b+=
g[u].multishowsAdd?"&"+g[u].multishowsAdd:""}function Lb(a){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+="&"+encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b}function Oa(a){return h(a.getClientRects)&&(a=a.getClientRects())&&h(a[0])&&h(a[0].right)&&h(a[0].left)?(a=a[0],{width:O(a.right-a.left),height:O(a.bottom-a.top)}):!1}function ed(a,b){return function(){if(b&&""!=b.innerHTML){var c=Oa(b);c&&N(L+"clickiocdn.com/area_size/?data="+a+","+c.width+","+c.height,function(){})}}}function fa(a,
b){a=Array.isArray(a)?a:[a];Ya.push({qa:a,oa:b})}function oc(a,b,c,d,f){f=f||ga;b.type=a;b.rnd=X();b.prefix=ga;c.postMessage(f+JSON.stringify(b),d)}function Ha(a,b,c,d,f){f=f||ga;b.type=a;oc("event",{event:b},c,d,f)}function pc(a,b){var c=r.getElementById(a);if(b){var d=r.querySelectorAll("#"+a),f;for(f in d)if(d.hasOwnProperty(f)&&"length"!=f&&d[f].getAttribute("data-cnt")==b){c=d[f];break}}return c}function qc(a){var b=!1,c=!0,c=rc(n(a.check)),d=n(a.location),f=n(a.location_max);if(c&&d)for(f?f=
t(f):f=1,c=null,1<f?c=r.querySelectorAll(d):c=[r.querySelector(d)],d=0;d<c.length&&!(d+1>f);d++){var g=c[d];if(g){var e=z("div");e.id=a.id;e.setAttribute("data-cnt",1+d);e.className="__lxG__multi __lxG__multi_"+a.id;g.parentNode.insertBefore(e,g.nextSibling)}b||(b=e)}return b}function Cb(a){var b=a.which?a.which:a.button;a=(ea?a.srcElement:a.target).nodeName.toLowerCase();"a"!=a&&"img"!=a||2==b||3==b||(clearTimeout(Db),Db=setTimeout(function(){Db=null;Za()},500))}function sc(a){a=a||!1;var b=[],c=
[];$a&&y(C,function(a){a=a.substr(1);g[u].bids.bidding&&(~g[u].bids.bidding.indexOf(a)||~g[u].bids.bidding.indexOf(t(a)))?c.push(encodeURIComponent(a)):b.push(encodeURIComponent(a))});return a?[b.join(";"),c.join(";")]:b.join(";")}function dd(a){a=a||sc();if(g[u].bids.bids){var b=!1,c="";y(a.split(";"),function(a,f){~ab.indexOf(f)||(y(g[u].bids.bids,function(a,d){if(d.id==f){if(d.bids.length){var k=[];y(d.bids,function(a,b){k.push(b.join("_"))});c+=k.join(",");b=!0}bb&&(ab.push(f),Ha("bidSent",{id:f},
g.top,"*",Ia));return!1}}),c+="-")});if(b)return c=c.substring(0,c.length-1)}return""}function tc(a){uc(a.target?a.target:a.srcElement)}function fd(a){var b=/\/(i)\/(a??)(\d+?)\//m,c=b.exec(a);null==c&&(b=/\/(ii)\/(a??)(\d+?)\//m,c=b.exec(a));var d=!1,f=!1;null!=c&&16!=c[3]&&(d=t(c[3]),d=(2*(10*d+40)-40)/10,16<=d&&(d=16),f=10*d+40,d=a.replace(b,"/$1/$2"+d+"/"));return{url:d,size:f}}function vc(a){var b=t("CSS1Compat"!=r.compatMode||g.opera?F.scrollTop:R.scrollTop),c=t(b+T()),d=t("CSS1Compat"!=r.compatMode||
g.opera?F.scrollLeft:R.scrollLeft),f=t(d+(ra&&!g.opera?R.clientWidth:F.clientWidth)),h=a.getClientRects()[0],e=O(h.top)+b,k=O(h.bottom)+b,l=O(h.left)+d,h=O(h.right)+d;e<b&&(a.style.top=t(a.style.top)+(b-e)+3+"px");k>c&&(a.style.top=t(a.style.top)-(k-c)-3+"px");l<d&&(a.style.left=t(a.style.left)+(d-l)+3+"px");h>f&&(a.style.left=t(a.style.left)-(h-f)-3+"px")}function zb(a){for(var b=0,c=0;a&&"relative"!=U(a).position&&"absolute"!=U(a).position;)b+=t(a.offsetTop),c+=t(a.offsetLeft),a=a.offsetParent;
return{top:b,left:c}}function U(a){return a.Ba=a.Ba||a.currentStyle||getComputedStyle(a,0)}function gd(a){return function(){a&&a.parentNode&&a.parentNode.removeChild(a)}}function uc(a){var b,c=zb(a),d=fd(a.src),f=d.size;if((d=d.url)&&d!=a.src){a.previousSibling&&"img"==a.previousSibling.nodeName.toLowerCase()?b=a.previousSibling:(b=a.cloneNode(!1),ea&&b.detachEvent("onmouseover",tc),b.style.position="absolute",b.style.top="-100000px",b.style.left="-100000px",b.style.margin="0px",b.style.maxWidth=
"",b.style.maxHeight="",A(b,"mouseout",function(){clearTimeout(~~b.getAttribute("enlrgTmr"));Ba(b,"shrTmr",setTimeout(function(){wc(b,a)},10))}),a.parentNode.insertBefore(b,a));if(b.src==a.src){var g=b.cloneNode(!1);A(g,"load",function(){b.src=g.src;setTimeout(gd(g),250)});g.src=d;b.parentNode.insertBefore(g,b)}b.width=a.width;b.height=a.height;b.style.top=c.top+"px";b.style.left=c.left+"px";a.style.visibility="hidden";a.parentNode.style.zIndex=1E5;vc(b);b.setAttribute("enlrgTmr",setTimeout(function(){xc(b,
f)},10))}}function wc(a,b){clearTimeout(~~a.getAttribute("enlrgTmr"));var c=zb(b),d=t(a.height)-10;a.width=t(a.width)-10;a.height=d;d=t(c.left)>t(a.style.left)?t(a.style.left)+5:t(a.style.left)-5;a.style.top=(t(c.top)>t(a.style.top)?t(a.style.top)+5:t(a.style.top)-5)+"px";a.style.left=d+"px";t(a.width)>t(b.width)?a.setAttribute("shrTmr",setTimeout(function(){wc(a,b)},10)):(a.style.top="-100000px",a.style.left="-100000px",b.style.visibility="",b.parentNode.style.zIndex="")}function xc(a,b){clearTimeout(~~a.getAttribute("shrTmr"));
var c=t(a.height)+10;a.width=t(a.width)+10;a.height=c;c=t(a.style.left)-5;a.style.top=t(a.style.top)-5+"px";a.style.left=c+"px";vc(a);t(a.width)<b&&a.setAttribute("enlrgTmr",setTimeout(function(){xc(a,b)},10))}function wb(){return"_lxretpopupignore"}function ac(a){a=E("lx_block_params",a);var b=a.length,c=[];if(b)for(var d=0;d<b;d++)for(var f=a[d].attributes,g=f.length,e;g--;)e=f[g],0===e.name.indexOf("data-")&&(c[e.name.replace("data-","")]=e.value);return c}function rc(a){return!1===a?!1:null!==
r.querySelector(a)}function Eb(a,b,c){xa=!0;b&&(a?(r.write('<script type="text/javascript" language="JavaScript" src="'+L+"clickiocdn.com/multishows/"+b+"/"+ja()+'">\x3c/script>'),xa=!1):N(L+"clickiocdn.com/multishows/"+b+"/"+ja(b),function(){xa=!1}));c&&(cb&&clearInterval(cb),cb=setInterval(function(a){return function(){var b=(new Date).getTime(),c=!g[u].bids.bidding;if(b>g[u].bids.start+db&&b<g[u].bids.start+db+100||c)Zc("Bidding:\n   started: "+(new Date(g[u].bids.start)).toISOString()+"\n   ended: "+
(new Date(g[u].bids.end)).toISOString()),clearInterval(cb),xa=!0,N(L+"clickiocdn.com/multishows/"+a+"/"+ja(a),function(){xa=!1})}}(c),50))}function Za(a){if(!xa){var b=sc(!0),c=b[0],b=b[1];if(!Ja&&(c||b)&&!Fb){var d=c.split(";"),f=b.split(";"),h=d.concat(f);y(h,function(a){~yc.indexOf(h[a])&&h.splice(a,1)});if(h.length){yc=h;Fb=!0;Gb=function(a,b,c){return function(d){d=d||[];Fb=Ka=!1;var f=[],g=[];y(b,function(a,b){~d.indexOf(""+b)||f.push(b)});y(c,function(a,b){~d.indexOf(""+b)||g.push(b)});Eb(a,
f.join(";"),g.join(";"))}}(a,d,f);Ha("getPreloadItems",{ids:h},g.top,"*",eb);Ka=setTimeout(Gb,100);return}}Eb(a,c,b)}}var C=w,r=document,g=window,F=r.body,R=r.documentElement,Da=function(a){a=a||r;html=a.documentElement;var b=Ga("head",!1,a);if(b)return b;for(b=html.firstChild;b&&"#text"==b.nodeName.toLowerCase();)b=b.nextSibling;if(b&&"#text"!=b.nodeName.toLowerCase())return b;a=z("head",a);html.appendChild(a);return a}(),Pa=t(p),u="__lxG"+Pa+"__",fb={},da=navigator.userAgent.toLowerCase(),hd=(navigator.userAgent.toLowerCase().match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||
[])[1],ra="CSS1Compat"===r.compatMode,sa=/chrome/.test(da),gb=/opera/.test(da),ea=/msie/.test(da)&&!gb,id=!window.ActiveXObject&&"ActiveXObject"in window,qa=!1,xa=!1,Db=null,$a=0,na=[],ua=null,mc=sa?cd():lc(),B={},Q="",zc=!1,Wa=ea&&(!ra||8>t(hd)&&ra),L="http"+("about:"==g.location.protocol?"https:"==g.top.location.protocol?"s":"":"https:"==g.location.protocol?"s":"")+"://",vb=L+"clickiocdn.com/real_show_log/?data=",P={},cc=!1,Ta=!1,Ua=!1,la=!1,qb=1,Xb=1,Yb=1,tb=0,sb=0,rb=!1,Sa=-1,Ab=!1,Hb="__lx"+
Pa,lb=Hb+"_load_cnt",Rb=Hb+"_load_tmr",Sb=Hb+"_load_tmr_pre",Ac=!1,cb=!1,db=3E3,nc=!0,Ib=5,Jb=null,Bb=[],pa=null,va=[],S={get:function(a,b){var c;this.T(a)?(c=r.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"),c=decodeURIComponent(c)||(h(b)?b:null)):c=h(b)?b:null;return c},set:function(a,b,c,d,f,g){if(!a||/^(?:expires|max\-age|path|domain|secure)$/i.test(a))return!1;var e="";if(c)switch(c.constructor){case Number:e=
Infinity===c?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+c;break;case String:e="; expires="+c;break;case Date:e="; expires="+c.toUTCString()}r.cookie=encodeURIComponent(a)+"="+encodeURIComponent(b)+e+(f?"; domain="+f:"")+(d?"; path="+d:"")+(g?"; secure":"");return!0},Ka:function(a,b,c){if(!a||!this.La(a))return!1;r.cookie=encodeURIComponent(a)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(c?"; domain="+c:"")+(b?"; path="+b:"");return!0},T:function(a){return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,
"\\$&")+"\\s*\\=")).test(r.cookie)},list:function(){for(var a=r.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/),b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);return a}},E=r.getElementsByClassName?function(a,b){return(b||document).getElementsByClassName(a)}:function(a,b){b=b||document;var c=b.getElementsByTagName("*"),d=c.length,f=a.split(/\s+/),g=f.length,e=[],k,l;for(k=0;k<d;k++)for(l=0;l<g;l++)if(~c[k].className.search("\\b"+f[l]+"\\b")){e.push(c[k]);
break}return e};A(g,"scroll",jc);fb[u]={};fb[u].ia=function(a){if(!Q)return!0;a=a||g.event;var b=(a.target||a.srcElement).nodeName.toLowerCase();if(ea&&"a"==b)return!0;Q+="?rnd="+X()+(g[u].Aa?"&"+g[u].Aa:"");gb?(g.open(Q,u+"popunder","resizable=1,toolbar=1,location=1,menubar=1,status=1,directories=0,width="+screen.availWidth+",height="+screen.availHeight),g.blur(),g.focus()):sa?Uc(Q,a):ea?ic(Q):id?Vc(Q):setTimeout(function(){ic(Q)},0);Ra(F,sa||gb?"mousedown":"click",fb[u].ia);return!0};var Ja=null;
h(g[u])||(g[u]={});h(g[u].instances)||(g[u].instances=[]);h(g[u].blocks)||(g[u].blocks={});h(g[u].bids)||(g[u].bids={bidding:!1,start:0,end:0,bids:!1});var ya=X(),W=u+ya;g[W]={};g[u].instances.push(ya);h(g.__lxG__)||(g.__lxG__={});db=n(g.__lxG__.biddingBlocksDelay,db);h(g[u].closed)||(g[u].closed=function(){},g[u].clicked=function(){});h(g[u].popunderShow)||(g[u].popunderShow=!1);h(g[u].allLoaded)||(g[u].allLoaded=function(){});h(g[u].popunderAdd)||(g[u].popunderAdd="");h(g[u].multishowsAdd)||(g[u].multishowsAdd=
"");var Ia=u,eb=u+"cache",ga=W,bb=g!=g.top,Bc=g.frameElement&&g.frameElement.id&&0===g.frameElement.id.indexOf("google_ads_iframe_"),Kb=[g.location.hostname],Cc=[];A(g,"message",function(a){if(a.data&&h(a.data.indexOf)&&(0===a.data.indexOf(ga)||0===a.data.indexOf(eb))&&~Kb.indexOf(a.origin.replace(/https?:\/\//img,""))){var b=0===a.data.indexOf(ga)?ga:eb,c=null;try{c=JSON.parse(a.data.replace(ga,"").replace(eb,""))}catch(d){return!1}c&&h(c.type)&&("codePing"==c.type&&a.source.postMessage(b+JSON.stringify({type:"codePong"}),
a.origin),"event"!=c.type||~Cc.indexOf(n(c.rnd))||(Cc.push(c.rnd),y(Ya,function(b){if(~Ya[b].qa.indexOf(c.event.type)&&0===Ya[b].oa(c.event,{source:a.source,origin:a.origin,prefix:n(c.prefix,Ia)}))return!1})))}});var Ya=[];fa("renderOver",function(a){if(Bc){var b=a.data[0],c=g.frameElement.parentNode.parentNode,d=c.parentNode,f=g.parent,h=f.document||f.contentDocument||f.contentWindow.document;wa(b.style);f=h.createElement("div");f.id=b.div_name;V(f,b.source,h);c.style.display="none";d.insertBefore(f,
c);I(b,h);y(a.data,function(a,b){if("counters"==b.type)return I(b,h),!1})}else{if(b=pc(n(a.data[0].div_name),n(a.data[0].sub_id)))b.innerHTML="";setTimeout(function(){g[W].parser(a.data)},0)}});fa("renderBidderOver",function(a){var b=a.data[0],c=a.id,d=a.num;a=a.bId;var f=X();if(Bc){var h=g.frameElement.parentNode.parentNode,e=g.parent,k=e.document||e.contentDocument||e.contentWindow.document;fa("bidHtml",function(a,c,d,e,g,k){return function(e){if(e.eventId==f){var g=d.createElement("div");g.id=
k;var h=a.getAttribute("style");Ba(a,"style",(h?h+";":"")+"display: none !important;");c.insertBefore(g,a);e.html&&!e.url?oa(g,e.html,e.w,e.h,d):!e.html&&e.url&&oa(g,e.url,e.w,e.h,d,!0);I(b,d);y(e.data,function(a,b){if("counters"==b.type)return I(b,d),!1});return-1}}}(h,h.parentNode,k,c,d,a))}else fa("bidHtml",function(a,b,c,d){return function(b){if(b.eventId==f){var c;if(n(a.sub_id)){var e=n(a.sub_id),g=r.querySelectorAll("#"+d);y(g,function(a){if(g[a].getAttribute("data-cnt")==e)return c=g[a],!1})}else c=
r.getElementById(d);c.innerHTML="";b.html&&!b.url?oa(c,b.html,b.w,b.h,k):!b.html&&b.url&&oa(c,b.url,b.w,b.h,k,!0);I(a,k);y(b.data,function(a,b){if("counters"==b.type)return I(b,k),!1});return-1}}}(b,c,d,a));Ha("getBidHtml",{id:c,num:d,eventId:f},g.top,"*",Ia)});bb&&(fa("bids",function(a){g[u].bids=a.bids}),oc("subscribe",{subscriber:{prefix:ga,events:["renderOver","renderBidder","renderBidderOver","bids","sentBids"]}},g.top,"*",Ia),Ha("getBids",{},g.top,"*",Ia));var ma=null,Sc=["cfg","params","get_area_size"],
Tc=["counters","iframe_counters"],xb=[];g[W].addPreload=function(a){var b=[];y(a,function(a,d){C[a]=d;b.push(a.replace("_",""))});Eb(0,b.join(";"),"")};fa("getPreloadItems",function(a,b){if(!Ja||!ma)return!1;var c=a.ids,d=!1,f=JSON.parse(JSON.stringify(xb)),g=[];y(c,function(a,b){n(ma[b])&&(d=!0,f.push(ma[b]),g.push(b))});d&&(y(g,function(a,b){delete ma[b]}),Ha("preloadItems",{preloadItems:f,found:g},b.source,b.origin,b.prefix))});g[W].parser=g[u].parser=function(a){na=[];var b=!1,c={},d;for(d in a)a.hasOwnProperty(d)&&
(e=a[d],n(e.sub_id)&&(b=!0),"params"==e.type?(c=e.blocks,y(c,function(a,b){h(b.ch_dmn)&&!~Kb.indexOf(b.ch_dmn)&&Kb.push(b.ch_dmn)})):"cfg"==e.type&&(Ac=n(e.isMobile)&&ob())&&Ib&&!Jb&&(Jb=setInterval(function(){return function(){Ib?(Ib--,H()):clearInterval(Jb)}}(),3E3)));var f=!1;y(a,function(b){var c=a[b];if(n(c.id)){var d=n(c.sub_id);b="_"+c.id;c=d?"_"+c.id+"."+d:!1;if(1==n((c?n(C[c]):n(C[b])).preload))f=!0;else return f=!1}});for(var p in a)if(a.hasOwnProperty(p)){var e=a[p];if("params"!=e.type&&
"cfg"!=e.type)if(!f&&"counters"==e.type){if(e.hasOwnProperty("urls"))for(var k=0;k<e.urls.length;k++)z("img").src=e.urls[k]+"&_lxrnd_="+X()}else if(!f&&"iframe_counters"==e.type){if(e.hasOwnProperty("sources"))for(k=0;k<e.sources.length;k++){d=e.sources[k];var l=z("iframe");l.id="__lxG__frame_tracker_"+k;l.sandbox="allow-same-origin allow-scripts allow-forms";l.style.width="1px";l.style.height="1px";l.setAttribute("allowtransparency","true");l.setAttribute("marginwidth","0");l.setAttribute("marginheight",
"0");l.setAttribute("hspace","0");l.setAttribute("vspace","0");l.setAttribute("frameborder","0");l.setAttribute("scrolling","no");l.src="javascript:'"+(d+"").replace(/[\\"']/g,"\\$&").replace(/\u0000/g,"\\0")+"'";F.appendChild(l)}}else if(f||"get_area_size"!=e.type){if("mdcheck"==e.type)return e.hasOwnProperty("url")&&N(L+e.url+(~e.url.indexOf("?")?"&":"?")+"f="+W),!0;if("mdparam"==e.type)return e.hasOwnProperty("param")&&(Ab=e.param,e.hasOwnProperty("alg")&&e.alg&&(vb=L+e.alg+".clickiocdn.com/real_show_log/?data="),
setTimeout(function(){Za(0)},0)),!0;if(!(f||(d=n(e.sub_id),l="_"+e.id,k=d?"_"+e.id+"."+d:!1,!k&&h(g[u].blocks[l])&&g[u].blocks[l]!=ya||k&&h(g[u].blocks[k])&&g[u].blocks[k]!=ya))){h(g[u].blocks[l])||(g[u].blocks[l]=ya);var m=k?n(C[k]):n(C[l]);if(!m)h(c[e.id])?m=c[e.id]:m={},C[k?k:l]=m;else if(h(c[e.id])){var q=["refresh_limit"];y(c[e.id],function(a){~q.indexOf(a)&&h(m[a])||(m[a]=c[e.id][a])})}if(h(m.debug)&&m.debug&&(l=!1,r.location.search?(k=$c(r.location.search),h(k.lx_debugmode)&&1==k.lx_debugmode||
(l=!0)):l=!0,l))continue;if(!h(m.location)&&r.getElementById(m.id)&&!r.getElementById(e.div_name)){var l=r.querySelectorAll("#"+m.id),w;for(w in l)l.hasOwnProperty(w)&&"length"!=w&&l[w].setAttribute("id",e.div_name)}m.id=e.div_name;h(m.location)||r.getElementById(m.id)||(l=document.createElement("div"),l.setAttribute("id",m.id),F.appendChild(l));if(h(m)&&h(e.source)){l=pc(m.id,d);!1===la&&(la=h(e.isTablet)?t(e.isTablet):0);if(l&&"html"==e.type&&e.source){qa||(wa(e.style),A(l,"click",Cb));l.innerHTML=
e.source;m.B=!0;var v=ac(l);m.Ja=v;h(e.real_show_log)&&e.real_show_log&&na.push([l,e.real_show_log]);if(n(v.lxm_responsive)){var x=l.querySelectorAll(".lx_anons"),k=0,k=function(a,b){return function(){Yc(a,n(b.lxm_fit_factor,1.5),{min:n(b.lxm_fit_min,14)+"px",max:n(b.lxm_fit_max,20)+"px"});y(a,function(a,c){Xc(c,{clamp:n(b.lxm_clamp)})})}}(x,v);setTimeout(k,50);setTimeout(k,250);setTimeout(k,500);setTimeout(k,1E3);setTimeout(k,2E3)}if(h(m.zoomImages)&&m.zoomImages)for(k=l.getElementsByTagName("img"),
v=k.length,x=0;x<v;x++)r.addEventListener?k[x].addEventListener("mouseover",function(){uc(this)},!1):k[x].attachEvent("onmouseover",tc);I(e);aa(m,d)}l&&"pu"==e.type&&!zc&&(e.hasOwnProperty("url")?Q=e.url:Q=L+"s.clickiocdn.com/pu/"+e.id+".html",e.hasOwnProperty("pattern")&&e.hasOwnProperty("timeout")?(k=S.get(Rb,0),(new Date).getTime()-k>6E4*e.timeout&&Qb(1),k=t(S.get(lb,0)),~e.pattern.indexOf(k)||~e.pattern.indexOf(7)&&7<=k||(Q=!1)):Q=!1,Q&&(A(F,sa||gb?"mousedown":"click",fb[u].ia),m.B=!0),zc=!0);
if("js"==e.type&&(k=n(m.ai_mode),m.L=Ac&&!n(e.mobATF)&&!n(e.isTablet),"js_npm"==n(m.type)&&n(m.check)&&n(m.location)&&!d&&(l&&l.parentNode.removeChild(l),k?(l=rc(m.check),l||(m.M=n(m.M,0),10>m.M&&(m.M||(m.Da=function(a,b,c){return function(){a[b].parser([c])}}(g,W,e)),setTimeout(m.Da,1E3),m.M++))):l=qc(m)),l)){qa||(h(e.style)&&wa(e.style),k||A(l,"click",Cb));!d&&n(m.add_meta)&&bc("width=device-width,initial-scale=1.0,maximum-scale=2.0,user-scalable=1");if(k&&!d){if(k=!h(m.c))m.c={K:!1,m:null,C:null,
D:[]};m.c.source=e.source;m.c.counters=n(e.counters,[]);m.c.id=e.id;k?(Qa(m),m.c.ha=function(a){return function(){!a.c.K&&ib(a)&&Qa(a);g.innerHeight+g.scrollY>=(R&&R.scrollHeight||F.scrollHeight)&&Ra(window,"scroll",a.c.ha)}}(m),A(window,"scroll",m.c.ha)):m.L&&T()>ia(l).top?(k=G(l,e.source))?(V(l,k),I(e),aa(m,d),K(l,{id:e.id,type:"npm_resized"})):K(l,{id:e.id,type:"npm"}):(V(l,e.source),I(e),aa(m,d));!n(m.ai_clone_source)&&m.c.m.length&&ib(m)&&(m.c.source=!1,Qa(m,!0))}else if(!n(m.ai_clone_source)&&
(m.L&&T()>ia(l).top?(k=G(l,e.source))?(V(l,k),I(e),aa(m,d),K(l,{id:e.id,type:"npm_resized"})):K(l,{id:e.id,type:"npm"}):(V(l,e.source),I(e),aa(m,d)),v=r.querySelectorAll("#"+m.id),!d&&(!b||n(m.location))&&v&&1<v.length))for(x=v.length;x;)l=v[x-1],1<v[x-1].getAttribute("data-cnt")&&(m.L&&T()>ia(l).top?(k=G(l,e.source))?(V(l,k),I(e),aa(m,d),K(l,{id:e.id,type:"npm_resized"})):K(l,{id:e.id,type:"npm"}):(V(l,e.source),I(e),aa(m,d))),x--;m.B=!0}if("iframe"==e.type){if(n(m.check)||n(m.location))l&&l.parentNode.removeChild(l),
l=qc(m);qa||h(e.style)&&wa(e.style);h(e.pre_source)&&V(l,e.pre_source);if(l){oa(l,e.source,e.width,e.height);I(e);aa(m,d);v=r.querySelectorAll("#"+m.id);if((!b||n(m.location))&&v&&1<v.length)for(x=v.length;x;)l=v[x-1],1<v[x-1].getAttribute("data-cnt")&&(h(e.pre_source)&&V(l,e.pre_source),oa(l,e.source,e.width,e.height),I(e),aa(m,d)),x--;m.B=!0}}l&&"float"==e.type&&(k=!1,qa||(wa(e.style),A(l,"click",Cb)),d=e.id,h(B[d])||(B[d]=C["_"+d],B[d].I=d,B[d].a=l,B[d].u=!1,B[d].G=!1,B[d].J=!1,B[d].l=0,B[d].o=
!1,B[d].X=!1,B[d].Y=!1,B[d].H=!1,h(e.real_show_log)&&e.real_show_log&&(B[d].X=!0,B[d].Y=e.real_show_log),k=!0),B[d].a.innerHTML=e.source,B[d].a.style[B[d].side]="-1000px",B[d].a.style.display="block",B[d].width=t(B[d].a.width?B[d].a.width:B[d].a.offsetWidth),B[d].a.style[B[d].side]=-B[d].width+"px",Qc(B[d],k),B[d].o&&(B[d].o=!1),gc(B[d])(),m.B=!0,I(e));l&&"mobile"==e.type&&(k=!1,qa||wa(e.style),d=e.id,h(P[d])||(P[d]=C["_"+d],P[d].I=d,P[d].a=l,P[d].G=!1,P[d].l=0,P[d].o=!1,k=!0),l.innerHTML=e.source,
m.B=!0,Mc(P[d],k),P[d].o&&(P[d].o=!1),I(e));e.hasOwnProperty("iframe_source")&&(oa(l,e.iframe_source,1,1),I(e));"inlinevideo"==e.type&&Dc(r.querySelector(n(m.location)),{Ga:e.video_url,aa:e.click_url,Fa:e.video_start_url,ka:e.video_end_url,F:n(e.video_trackers,!1),Ha:e.width,Ea:e.height,ga:n(e.overlay_html,""),ba:n(e.full_view_percent,100),R:n(m.width),na:n(m.style),ra:n(m.hideClose),sa:n(m.hideMarker),ca:n(m.hidePostblock)})}}}else if(e.hasOwnProperty("ids"))for(d=0;d<e.ids.length;d++)l=e.ids[d],
h(C["_"+l])&&setTimeout(ed(l,r.getElementById(C["_"+l].id)),3E3)}if(f){var E=[];y(a,function(b){b=a[b];if(n(b.id)){var c=n(b.sub_id),d="_"+b.id,c=c?"_"+b.id+"."+c:!1;1==n((c?n(C[c]):n(C[d])).preload)&&E.push(b)}else E.push(b)});Rc(a);return!0}for(var J in C)C.hasOwnProperty(J)&&!h(C[J].B)&&h(C[J].cap)&&C[J].cap();qa=!1;setTimeout(function(){g[u].allLoaded()},0);jc()};var ab=[];bb&&fa("sentBids",function(a){ab=ab.concat(n(a.bids,[]))});var pb=!1,Ob=!1,ta=[],Z=[],Ca=[],Fb=!1,yc=[],Gb=!1,Ka=!1;fa("preloadItems",
function(a){Ka&&(clearTimeout(Ka),Ka=!1,setTimeout(function(){g[W].parser(a.preloadItems)},0),setTimeout(function(){Gb(a.found)},0))});Qb(t(S.get(lb,0))+1);(function(){var a=!1;h(g.__lxG__.multishows_params)&&h(g.__lxG__.multishows_params.singleton)&&(a=g.__lxG__.multishows_params.singleton);y(C,function(b){var c=!1;a&&a!=b.replace("_","")&&(c=!0);var g=r.getElementById(C[b].id);!0===n(C[b].preload)?(g=!0,null===Ja&&(Ja=!0)):Ja=!1;c||"float"!=n(C[b].type)||S.T(wb())&&(c=!0);!g||c?delete C[b]:$a+=
1});var b=S.list(),c;for(c in b)b.hasOwnProperty(c)&&0===b[c].indexOf("_lxblockignore_")&&Bb.push(b[c].replace("_lxblockignore_",""));$a&&y(C,function(a){a in g[u].blocks?delete C[a]:!0!==n(C[a].preload)&&(g[u].blocks[a]=ya)})})();bb?setTimeout(function(){Za(0)},100):Za(0);return W}var ha=document,p=window;p.__lxGc__=p.__lxGc__||{s:{},b:0};p.__lxGp__=p.__lxGp__||{s:{}};if(p.__lxGc__.f)return setTimeout(p.__lxGc__.f,0),!1;var Aa=Object.create;"function"!==typeof Aa&&(Aa=function(p){function v(){}v.prototype=
p;return new v});var La={},za={};p.__lxGc__.f=function(){J(p.__lxGp__.s,function(v){var q=Ma(p.__lxGp__.s[v].b,[]);if(q.length){q=M(q);p.__lxGp__.s[v].b=[];var H={};J(q,function(p){p=q[p];var v;v="undefined"!=typeof za[p]?++za[p]:1;za[p]=v;H[1<v?p+"."+v:p]={preload:!0}});Ma(La[v])?p[La[v]].addPreload(H):La[v]=Na(v.replace("_",""),0,H)}});if(p.__lxGc__.b&&p.__lxGc__.b!==p.__lxGc__["b`"]){p.__lxGc__["b`"]=p.__lxGc__.b;p.__lxGc__["s`"]?J(p.__lxGc__.s,function(q){p.__lxGc__["s`"][q]?J(p.__lxGc__.s[q].b,
function(w){p.__lxGc__["s`"][q].b[w]?(p.__lxGc__["s`"][q].b[w].i=p.__lxGc__.s[q].b[w].i,p.__lxGc__["s`"][q].b[w].ver=p.__lxGc__["s`"][q].b[w].ver||0,p.__lxGc__["s`"][q].b[w].ver++):(p.__lxGc__["s`"][q].b[w]=M(p.__lxGc__.s[q].b[w]),p.__lxGc__["s`"][q].b[w].ver=0)}):p.__lxGc__["s`"][q]=M(p.__lxGc__.s[q])}):p.__lxGc__["s`"]=M(p.__lxGc__.s);var q=ha.querySelectorAll(".__lxGc__");if(!q.length)return!1;J(p.__lxGc__["s`"],function(v){var w=0,H={};J(p.__lxGc__["s`"][v].b,function(K){var G=p.__lxGc__["s`"][v].b[K];
if(!G._d||"undefined"!=typeof G.cnt&&G.cnt!=G.i+1){p.__lxGc__["s`"][v].b[K]._d=!0;G.id=G.id||"lx"+K;G.cnt=G.cnt||0;var M=new RegExp("\\[(?:'|\")b(?:'|\")\\]\\[(?:'|\")"+K+"(?:'|\")\\]","im");J(q,function(p){if((M.test(q[p].text)||"div"===q[p].nodeName.toLowerCase()&&q[p].nextElementSibling&&"script"===q[p].nextElementSibling.nodeName.toLowerCase()&&M.test(q[p].nextElementSibling.text)||"div"===q[p].nodeName.toLowerCase()&&q[p].getElementsByTagName("script").length&&M.test(q[p].getElementsByTagName("script")[0].text))&&
!q[p].getAttribute("data-cnt")){q[p].setAttribute("data-cnt",++G.cnt);var v=document.createElement("div");v.setAttribute("id",G.id);v.setAttribute("data-cnt",G.cnt);v.className="__lxG__multi __lxG__multi_"+G.id;q[p].parentNode.insertBefore(v,q[p]);1==G.cnt?H[K]=G:H[K+"."+G.cnt]=G;w++}})}});w&&Na(v.replace("_",""),M(p.__lxGc__["s`"][v]),M(H))})}};p.__lxGc__.f();"complete"!==ha.readyState&&(p.__lxGc__.t=setInterval(p.__lxGc__.f,10),ha.addEventListener("readystatechange",function(){"complete"==ha.readyState&&
(clearInterval(p.__lxGc__.t),delete p.__lxGc__.t,p.__lxGc__.f())},!1))})();
